### PR TITLE
Operational Insights compatibility

### PR DESCRIPTION
**Pull request by NComandini**
### Fixed
- It's not possible to set an Ingress class name with a Kubernetes version >1.22.X. Add IngressClassName value in spec section for any ingress. A different value can be set on each ingress. Adding some verifications to force usage of IngressClassName.

### Changed
- Add Horizontal Pod Autoscaler capability on the APITRAFFIC deployment.
- Add filebeat sidecar for Operational Insights component (ELK) on pods apitraffic and apimgr.
- Add new volume for audit logs on apimgr pod.

### CODE REVIEW

**Comment by NComandini** [comment]
@rathnapandi Please review the code.

**Review by rathnapandi — COMMENTED** [review]
I do see that elastic recommends to run filebeat as daemonset. but we are using as sidecar. 
Can we document why do we choose sidecar approach?

**Comment by NComandini** [comment]
Agree but the filebeat deployment in daemonset is already done with the Operational analytics helmchart.
So it's not necessary to add this kind of deployment.
Deploy sidecar can make sense for large cluster without capabability to segregate the deployment with nodeSelector.
I describe it in the filebeat section on the default values.yaml file.

**Review by rathnapandi — APPROVED** [review]
Looks good to me

**Pull request merged**
